_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 33
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 77
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 33
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 77
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.8.18
            "5": 0.18.3
            "6": 4.38.2
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
accelerator:
    value: gpu
batch_size:
    value: 16
bert_hidden_dim:
    value: 768
bert_name:
    value: scibert
check_val_every_n_epoch:
    value: 1
cross_attention_freq:
    value: 2
devices:
    value: 0,1,2,3
drop_ratio:
    value: 0
filename:
    value: stage1_test
gin_hidden_dim:
    value: 512
gin_num_layers:
    value: 5
gtm:
    value: true
init_checkpoint:
    value: ""
init_lr:
    value: 0.0001
lm:
    value: true
lr_decay_rate:
    value: 0.9
match_batch_size:
    value: 16
max_epochs:
    value: 5
min_lr:
    value: 1e-05
mode:
    value: train
num_query_token:
    value: 8
num_workers:
    value: 4
precision:
    value: bf16-mixed
projection_dim:
    value: 256
rerank_cand_num:
    value: 8
retrieval_eval_epoch:
    value: 50
root:
    value: /scratch/scratch/weili3
save_every_n_epochs:
    value: 1
scheduler:
    value: linear_warmup_cosine_lr
seed:
    value: 42
temperature:
    value: 0.1
text_max_len:
    value: 128
tune_gnn:
    value: true
warmup_lr:
    value: 1e-06
warmup_steps:
    value: 1000
weight_decay:
    value: 0.05
